### ISSUE TITLE
What is the cause of this error?

### ISSUE THREAD

**Issue by xxlunch** [CyberMiles/lity#7]
Start the Main Network
![d6eeed2f397439b0fde78597f03387dc](https://user-images.githubusercontent.com/44078281/47059773-50f58980-d1fd-11e8-9caf-03f803ad3476.png)

**Comment by hydai** [comment]
Hi, do you run `travis node init` before running `travis node start`?
The error `panic: no such table: governance_proposal` looks like that the database of travis is not initialized.

And this issue is related to `travis`, please forward this issue to [travis issues](https://github.com/CyberMiles/travis/issues). Thanks.
